name: "Manual dispatch"

on:
  push:
    branches: [main]
    paths:
      - "**.html"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone the project"
        run: echo "Checkout project"
  build:
    needs: [checkout]
    runs-on: ubuntu-latest
    steps:
      - name: "build the project"
        run: echo "Build project"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: "Run tests"
        run: echo "Run test cases"
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy project"
        run: echo "Deploy the project"
